version: '3'

services:
  deno_devcontainer:
    build:
      context: .
      dockerfile: dockerfile
    container_name: deno_devcontainer
    volumes:
      - .:/workspace
    ports:
      - '8080:8080'
