/* eslint-disable jsx-a11y/anchor-is-valid */
/* eslint-disable react-hooks/exhaustive-deps */
import Head from 'next/head';
import { useCallback, useEffect, useState } from 'react';
import styles from 'src/styles/Home.module.css';
import useSWR from 'swr';
import { useRouter } from 'next/router';


export default function Home() {
  const router = useRouter();
  const { data, error } = useSWR(
    'https://jsonplaceholder.typicode.com/posts/1'
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{router.query.id}</h1>
      </main>
    </div>
  );
}
